package com.huawei.agc.clouddb.myquickstart.model

import com.huawei.agconnect.cloud.database.CloudDBZoneObject
import com.huawei.agconnect.cloud.database.annotations.IsIndex
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey

/**
 * Definition of ObjectType Book.
 * Class Autogenerated from the console (developer account)
 *
 * @since 2020-05-19
 */
class Book(
    @PrimaryKey
    var id: Int? = null,

    @IsIndex(indexName = "bookName")
    var bookName: String? = null,

    var description: String? = null
): CloudDBZoneObject()