package com.huawei.agc.clouddb.myquickstart.model

import com.huawei.agconnect.cloud.database.ObjectTypeInfo

/**
 * Definition of ObjectType Helper.
 * Class Autogenerated from the console (developer account)
 *
 * @since 2020-05-19
 */
private const val FORMAT_VERSION = 1
private const val OBJECT_TYPE_VERSION = 5

fun getObjectTypeInfo(): ObjectTypeInfo {
    val objectTypeInfo = ObjectTypeInfo()
    objectTypeInfo.formatVersion = FORMAT_VERSION
    objectTypeInfo.objectTypeVersion = OBJECT_TYPE_VERSION.toLong()
    objectTypeInfo.objectTypes = listOf(Book::class.java)
    return objectTypeInfo
}
